### ISSUE TITLE
Limit by entity/block group

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/addon-limits#12]
Thinking about the incoming entity limits, we used to have animal limit on Askyblock but here we wouldn't.

So I've thought about limiting "groups"

```
groups:
   animals:
       - WOLF
       - COW
       - CHICKEN
       - VILLAGER
   hostile:
       - ZOMBIE
       - CREEPER
       - SPIDER
```
Then we could limit the group, instead of the entity itself. So a limit of 10 for animals, users could have (5 wolf and 5 cow) or (1 cow, 9 villagers), etc.

This could be expanded to block groups, not just entity. So we could create "redstone" group.
